### ISSUE TITLE
Segmentation Fault in L3 microbenchmark

### ISSUE THREAD

**Issue by shekharshank** [stanford-mast/iBench#5]
Hi, I am starting to use iBench, however when I run l3 microbenchmark, it gives segmentation fault  on an Intel machine at line 111 i.e.:
```
memcpy(block, block+CACHE_SIZE/2, CACHE_SIZE/2);
```

This is the error message when debugged:
```
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:152
```

The program works fine on AMD machine.

**Comment by shelbyt** [comment]
Having the same problem here as well. Relevant CPU and kernel information below:

![image](https://cloud.githubusercontent.com/assets/1332316/23495552/2e84f088-fece-11e6-9542-7f16e4f8b9ca.png)

**Comment by shelbyt** [comment]
Having the same problem here as well. Relevant CPU and kernel information below:

![image](https://cloud.githubusercontent.com/assets/1332316/23495575/5a9c53b4-fece-11e6-9707-d67111c488f1.png)
